### ISSUE TITLE
群名更新获取问题

### ISSUE THREAD

**Issue by tw1158** [juzibot/wxwork-tester#15]
1. 由别人邀请加入群聊
2. 群主改群聊名后，获取到的群名是之前的，改名事件不会触发
3. 多次修改群聊名，获取到的都是第一次加入群聊的那个名字，修改的获取不了

bot
  .on("scan", onScan) // 机器人需要扫描二维码时监听
  .on("room-join", onRoomJoin) // 加入房间监听
  .on("message", onMessage(bot)) // 消息监听
  .on('room-topic', async (room, topic, oldTopic, changer) => {
    console.log("Topic  :" + topic)
    console.log("oldTopic  :" + oldTopic)
  })
  .on('logout', (user,reason) => {
      console.log(`user ${user} logout:${reason}`)
    })
  .start();

**Comment by su-chang** [comment]
抱歉，我们这边没有复现该问题，请提供下修改群名称的详细信息：

修改前名称，修改后名称，修改时间点

当前群是外部群聊还是内部群聊

将以上信息及对应token反馈给JuziBot，我们这边查日志看看。
