### ISSUE TITLE
文件消息发送无效

### ISSUE THREAD

**Issue by Seventh-sun** [juzibot/wxwork-tester#16]
我将图片上传至oss获取图片地址后，使用生成filebox
`0|bot_server  |   FileBox {
0|bot_server  |   name: '1606990329896_20201124115040.png',
0|bot_server  |   boxType: 2,
0|bot_server  |   mimeType: 'image/png',
0|bot_server  |   remoteUrl: 'http://wedo918map.oss-cn-shenzhen.aliyuncs.com/work_wechat/0/1606990329896_20201124115040.png'`
但却一直发送不出去，也没有任何错误提示。

**Comment by su-chang** [comment]
请提供发送请求的时间点，以便我们这边查对应日志。将对应token和当前链接发到对应服务支持群。感谢配合。
