### ISSUE TITLE
延时导致消息转发多次。

### ISSUE THREAD

**Issue by 18986162971** [juzibot/wxwork-tester#17]
Error: 13 INTERNAL: TIMEOUT: RequestId: MT_ROOM_ADD_MEMBERS_MSG-R:10696053260027680-1688854005364293, counter: 2
    at Object.exports.createStatusError (/data/wwwroot/bot/bot-yikeyiqun-we/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/data/wwwroot/bot/bot-yikeyiqun-we/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/data/wwwroot/bot/bot-yikeyiqun-we/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/data/wwwroot/bot/bot-yikeyiqun-we/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/data/wwwroot/bot/bot-yikeyiqun-we/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 13,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'TIMEOUT: RequestId: MT_ROOM_ADD_MEMBERS_MSG-R:10696053260027680-1688854005364293, counter: 2'

**Comment by su-chang** [comment]
标题与内容无关，请认真描述问题。

BTW, 时间属性是日志不可或缺的一部分。

MT_ROOM_ADD_MEMBERS_MSG 表明添加好友超时，需要确定下是否拉人过于频繁。

**Comment by 18986162971** [comment]
11:30:59 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 14 UNAVAILABLE: TCP Write failed
杨谈芳 不存在
11:30:59 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 14 UNAVAILABLE: TCP Write failed
服务员 不存在
11:30:59 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 14 UNAVAILABLE: TCP Write failed
岳小凤 不存在
11:30:59 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 14 UNAVAILABLE: TCP Write failed
周雄涛 不存在
11:30:59 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 14 UNAVAILABLE: TCP Write failed
杨谈芳 不存在
11:30:59 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 14 UNAVAILABLE: TCP Write failed
服务员 不存在
11:30:59 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 14 UNAVAILABLE: TCP Write failed
岳小凤 不存在
11:30:59 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 14 UNAVAILABLE: TCP Write failed
周雄涛 不存在
11:30:59 ERR PuppetHostie stop() stop GRPC rejection: 2 UNKNOWN: Stream removed
&nbsp;user Contact<客服-小索&gt; logout





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "juzibot/wxwork-tester"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月11日(星期五) 中午11:58
收件人:&nbsp;"juzibot/wxwork-tester"<wxwork-tester@noreply.github.com&gt;;
抄送:&nbsp;"坚强"<23220821@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [juzibot/wxwork-tester] 延时导致消息转发多次。 (#17)





 
标题与内容无关，请认真描述问题。
 
BTW, 时间属性是日志不可或缺的一部分。
 
MT_ROOM_ADD_MEMBERS_MSG 表明添加好友超时，需要确定下是否拉人过于频繁。

**Comment by su-chang** [comment]
目前怀疑对于 bot.Contact.findAll() 调用频次较高。需要检查下对应的逻辑，结合自己的业务逻辑进行本地缓存。
