### ISSUE TITLE
机器人自动退出登录：ERR PuppetHostie stop() stop GRPC rejection: 2 UNKNOWN: Stream removed  user Contact<客服-小索> logout

### ISSUE THREAD

**Issue by 18986162971** [juzibot/wxwork-tester#18]
ERR PuppetHostie stop() stop GRPC rejection: 2 UNKNOWN: Stream removed
 user Contact<客服-小索> logout

**Comment by su-chang** [comment]
请提供相对完整的日志信息，以便我们快速排查并定位问题。

WECHATY_LOG=silly node index.js 可以打印详细日志。

需要提供下 PuppetHostie stop() 之前有什么操作行为。

**Comment by su-chang** [comment]
wechaty版本没有更新导致的，已解决。

**Comment by 18986162971** [comment]
收到，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "juzibot/wxwork-tester"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 晚上7:39
收件人:&nbsp;"juzibot/wxwork-tester"<wxwork-tester@noreply.github.com&gt;;
抄送:&nbsp;"坚强"<23220821@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [juzibot/wxwork-tester] 机器人自动退出登录：ERR PuppetHostie stop() stop GRPC rejection: 2 UNKNOWN: Stream removed  user Contact<客服-小索&gt; logout (#18)





 
wechaty版本没有更新导致的，已解决。
