### ISSUE TITLE
不加企业微信号为好友的话，无法在onMsg()方法中收到群消息

### ISSUE THREAD

**Issue by bsknight** [juzibot/wxwork-tester#20]
不加企业微信号为好友的话，无法在onMsg()方法中收到群消息

wechaty版本号： 0.50.7

## 1. Describe the bug
不加企业微信号为好友的话，个微在外部群内发送的消息，无法在message事件回调方法中被读取到
群为外部群，个微在群内发言，不加企业微信号的机器人好友的话，读取不到消息

## 2. To Reproduce
不加好友，个微在外部群中发言，观察程序message事件回调方法中的输出 （此个微以前不能为机器人账号好友，如果以前为好友，再删除好友，不能复现）
加好友后，等待五六个小时后，才可以收到该个微发送的群消息。

## 3. Full Output Logs
没有errorlog

**Comment by ray7551** [comment]
@bsknight 你不是一个人！我也碰到同样问题，已经折腾两天了。我以为是账号问题，换了其它账号也出现同样问题。

**Comment by bsknight** [comment]
> @bsknight 你不是一个人！我也碰到同样问题，已经折腾两天了。我以为是账号问题，换了其它账号也出现同样问题。
> 关于复现那一步，不同的是，我试验机器人和个微双向删除好友，应用重新启动后即可复现。

哦哦 我只删除了个微好友，  所以没能复现， 看来只要没有双向好友就不行，

**Comment by su-chang** [comment]
感谢反馈，这个问题正在修复中，修复后会统一升级。

**Comment by su-chang** [comment]
该问题已修复，请核查该问题，如果没有问题，请关闭该issue。感谢。

**Comment by bsknight** [comment]
> 该问题已修复，请核查该问题，如果没有问题，请关闭该issue。感谢。
谢谢，是否需要更新wechaty?

**Comment by su-chang** [comment]
不需要
