### ISSUE TITLE
购买链接404

### ISSUE THREAD

**Issue by suhli** [juzibot/wxwork-tester#26]
> https://qiwei.juzibot.com/corpPremium/wechaty
![image](https://user-images.githubusercontent.com/23626907/104272256-b6697b00-54d7-11eb-94a7-05842c863bab.png)

404了..还有请问有客服联系方式吗?

**Comment by lijiarui** [comment]
错过了这个issue，链接是： https://qiwei.juzibot.com/user/login?isWechaty=true 请检查是否正确。

另外，可以联系客服： juzibot

**Comment by suhli** [comment]
> 错过了这个issue，链接是： https://qiwei.juzibot.com/user/login?isWechaty=true 请检查是否正确。
> 
> 另外，可以联系客服： juzibot

点文档的链接过去的,客服的话联系到了
