### ISSUE TITLE
message不能获取图文信息

### ISSUE THREAD

**Issue by lightlzm** [juzibot/wxwork-tester#27]
向企业微信转发图文，但message不能收到图文信息。

console.log(msg)返回如下：

WechatifiedMessage {
  domain: null,
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '1112907',
  payload:
   { filename: '',
     fromId: '7881303435092545',
     id: '1112907',
     mentionIdList: [],
     roomId: '',
     text: '',
     timestamp: 1610594369000,
     toId: '1688851962138244',
     type: 14 } }

可以修复下吗？

**Comment by su-chang** [comment]
```ts
const urlLinkPayload = await message.toUrlLink()
```

see: https://github.com/wechaty/wechaty/blob/473e20ba420ff20f20250295b9b4b1a09f4c3608/src/user/message.ts#L1007-L1025
