### ISSUE TITLE
13 INTERNAL: ERR_CONTACT_ID, can not get contact card message by contactId:xxxxxxxxx

### ISSUE THREAD

**Issue by liuxiaojinla** [juzibot/wxwork-tester#30]
Error: 13 INTERNAL: ERR_CONTACT_ID, can not get contact card message by contactId: xxxxxxxxx

**Comment by liuxiaojinla** [comment]
一个添加微信好友的程序，现在一直会添加失败，失败原因：13 INTERNAL: ERR_CONTACT_ID, can not get contact card message by contactId:xxxxxxxxx
`
async function addFriend(phone) {
	for (let i = 0; i < 2; i++) {
		try {
			return _.bot.Friendship.search({
				phone: phone,
				// weixin: 'xxxx',
			}).then(function (contact) {
				if (!contact) {
					console.log('not found friend by phone to ' + phone);
					return null;
				}

				console.log('find friend by phone to ' + phone, contact.name());
				const userSelf = _.user.getUser();
				const name = userSelf.payload.name;
				return _.bot.Friendship.add(contact, name + '正在邀请你添加他为好友！').then(function () {
					console.log('add friend by search the ' + phone, contact.name());
					return contact;
				}, function (err) {
					console.warn('add friend fail by ' + phone, contact.name());
					return Promise.reject(err);
				});
			});
		} catch (e) {
			if (i === 1) {
				throw e;
			} else {
				log.error("首次搜索并添加失败，进行重试", e.message);
			}
		}

		await wait(1000);
	}
}
`

**Comment by su-chang** [comment]
Related issue: https://github.com/juzibot/wxwork-tester/issues/31
