### ISSUE TITLE
无法加载所有的群聊信息

### ISSUE THREAD

**Issue by NineSpinZ** [juzibot/wxwork-tester#42]
self.puppet.room_list()无法获取所有的群聊信息。我企业微信号有好几百个群，但是只加载出了70多个。

尝试了：
用其他号找到同一个群的room_id。然后room = self.Room.load(room_id),room.ready(force_sync=True)也没成功。参考了文档：
https://wechaty.gitbook.io/wechaty/v/zh/faq#room-list-not-complete

**Comment by su-chang** [comment]
**背景信息**
企业微信/微信 均无法在初次登陆时加载所有手机端存在的群信息，只会加载部分活跃群聊。

**解决办法**
1. 群里有人发送过消息，群内有修改群名/拉人进群的事件发生；
2. 将群聊添加到通讯录，重新登录后可以加载到这些群聊数据；

**Comment by NineSpinZ** [comment]
好的，谢谢。
