### ISSUE TITLE
服务器登陆不上，我是购买的puppet

### ISSUE THREAD

**Issue by CashunterXie** [juzibot/wxwork-tester#45]
> wechaty-puppet-padlocal-demo@0.1.2 demo /usr/share/nginx/html/wechat/wxwork
> ts-node main.ts

11:24:23 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds...
11:24:34 WARN No endpoint when starting grpc client, 9 retry left. Reconnecting in 10 seconds...

**Comment by su-chang** [comment]
see: https://github.com/wechaty/puppet-padlocal/issues
