### ISSUE TITLE
企业微信能否设置好友标签？

### ISSUE THREAD

**Issue by NineSpinZ** [juzibot/wxwork-tester#46]

**Comment by NineSpinZ** [comment]
企业微信能否设置好友标签？

尝试了:   
await self.puppet.tag_contact_add(tag_id='1', contact_id='test'). 

企业微信会报错，个人微信是正常的

**Comment by NineSpinZ** [comment]
@su-chang

**Comment by su-chang** [comment]
暂不支持。
