### ISSUE TITLE
can't fetch endpoint from chatie server

### ISSUE THREAD

**Issue by VEADoc** [juzibot/wxwork-tester#56]
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/22616515/160567099-9a70a2eb-029a-4bf2-b652-50dd43fe0a9c.png">
token登录不上 在浏览器中访问的到返回如下

<img width="533" alt="image" src="https://user-images.githubusercontent.com/22616515/160567354-717d2334-f70d-40d7-aca9-cc2b8caa280e.png">

**Comment by VEADoc** [comment]
@su-chang

**Comment by vkm0303** [comment]
请问怎么解决的
