### ISSUE TITLE
建群timeout

### ISSUE THREAD

**Issue by Seventh-sun** [juzibot/wxwork-tester#6]
在使用Room.create(contactList, [topic])接口的时候
会返回ERR Room create() exception: Error: 13 INTERNAL: TIMEOUT: RequestId: MT_CREATE_ROOM_MSG-7881299476913065|7881299872972189, counter: 1错误
在机器人上可以看到建群已经是被创建的了，但是topic也并没有生效

**Comment by Seventh-sun** [comment]
确定邀请建群的成员都是好友关系

**Comment by su-chang** [comment]
需要提供详细日志，以便根据日志查询问题。
