### ISSUE TITLE
无法发送视频 发送无报错 视频链接

### ISSUE THREAD

**Issue by ssl123** [juzibot/wxwork-tester#66]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/25582170/184795920-283922e0-3550-42a4-b026-e079245c9e8d.png">

视频链接：http://kmkj.devstatic.bxdaka.com/douyin/202202/09/216f3f25d1.mp4

**Comment by su-chang** [comment]
Please replace `wechaty` module by `@juzi/wechaty` module, and then try again.

**Comment by ssl123** [comment]
1
