### ISSUE TITLE
时常出现监听不到room-join和room-leave事件

### ISSUE THREAD

**Issue by Seventh-sun** [juzibot/wxwork-tester#8]
对应事件动作方法无响应内容，无相关日志提供

**Comment by su-chang** [comment]
提供相关复现步骤，或者展示下你处理该部分逻辑的代码。

**Comment by Seventh-sun** [comment]
`const bot = new Wechaty({
                puppet: 'wechaty-puppet-hostie',
                puppetOptions: {
                    token,
                }
            });
bot
.on('room-join', async () => {
            console.log("room-join")
         //无响应
})
.on('room-leave', async () => {
    console.log("room-leave")
 //无响应
 })
`

**Comment by su-chang** [comment]
你没有调用`bot.start()`方法

**Comment by Seventh-sun** [comment]
有调用的，我只是拿这部分的代码来解释而已，想message 是能监听到消息事件的，但是room-join和room-leave有时候无效

**Comment by su-chang** [comment]
需要提供下`有时无效`该场景的特征或复现步骤，方便我们排查问题。
