### ISSUE TITLE
无法连接节点，功能无法使用，报错如图

### ISSUE THREAD

**Issue by phillipyuan** [juzibot/wxwork-tester#82]
![image](https://user-images.githubusercontent.com/26888403/203707293-23149f68-37f5-4b0c-92e8-d71a784289a4.png)
报错如图，已经好几天连不上了，之前都能连上的。

**Comment by su-chang** [comment]
需要将token信息提供给JuziBot，我们这边需要处理下。

**Comment by phillipyuan** [comment]
好的，我们这边已经能用了。


感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "juzibot/wxwork-tester"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [juzibot/wxwork-tester] 无法连接节点，功能无法使用，报错如图 (Issue #82)





 
已处理
